services:
  mtx:
    image: jlesage/mkvtoolnix:latest
    container_name: mkvpeel
    environment:
#      - USER_ID=1026
#      - GROUP_ID=100
      - TZ=Europe/Moscow
      - RUST_LOG=info,mkvpeel=debug
    volumes:
      - ./target/x86_64-unknown-linux-musl:/target
      - ./in:/downloads:ro
      - ./out:/movies2:rw
#      - /volume3/downloads:/downloads:ro
#      - /volume2/video:/video:ro
#      - /volume1/movies1:/movies1:rw
#      - /volume2/movies2:/movies2:rw
#    working_dir: "/"
#    restart: unless-stopped
    entrypoint:
      - /target/release/mkvpeel
      - --src=/downloads
      - --dst=/movies2
      - --languages=en,ru
      - --buff=a:c:A_TRUEHD:1000
      - --buff=a:c:A_EAC3:100
      - --buff=a:c:A_AC3:10
      - --buff=a:c:A_DTS:-10
      - --buff=a:n:пучков:1000
      - --buff=a:n:comment:-1000
      - --buff=a:n:коммент:-1000
      - --buff=s:c:S_TEXT/UTF8:100
      - --buff=s:c:S_HDMV/PGS:10
      - --buff=s:n:пучков:1000
      - --buff=s:n:full:100
      - --buff=s:n:sdh:-100
      - --buff=s:n:форс:-100
      - --buff=s:n:comment:-1000
      - --buff=s:n:коммент:-1000
